# Generated by Django 5.0.3 on 2024-03-27 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
