# Generated by Django 5.0.3 on 2024-04-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_message_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(default='', upload_to='photos/messages'),
        ),
    ]
